from __future__ import annotations

from .gm import GM_PROGRAM_NAMES
from .core import (
    AudioItem,
    DEFAULT_PREVIEW_SPEED,
    MusicChannelSummary,
    OplInstrumentPatch,
    OplOperatorParams,
    SoundCardMusicHeader,
    build_audio_atlas,
    describe_music_channels,
    describe_opl_patch,
    describe_opl_patches_for_music,
    describe_soundcard_music_header,
    load_opl_instrument_table,
    parse_game_audio_stream,
    parse_note_pairs,
    parse_pc_speaker_preview_tracks,
    pc_speaker_preview_duration_seconds,
    soundcard_music_header,
    soundcard_music_offsets,
    synthesize_soundcard_music_wav,
    synthesize_wav,
    synthesize_ym3812_wav,
    write_midi,
    write_opl_full_register_trace_csv,
    write_opl_register_trace_csv,
    write_opl_vgm,
)
from .playback import play_audio_file, play_audio_item_realtime, render_preview_async, start_audio_preview_async, stop_audio_playback, temp_preview_wav

__all__ = [
    "AudioItem",
    "DEFAULT_PREVIEW_SPEED",
    "GM_PROGRAM_NAMES",
    "MusicChannelSummary",
    "OplInstrumentPatch",
    "OplOperatorParams",
    "SoundCardMusicHeader",
    "build_audio_atlas",
    "describe_music_channels",
    "describe_opl_patch",
    "describe_opl_patches_for_music",
    "describe_soundcard_music_header",
    "load_opl_instrument_table",
    "parse_game_audio_stream",
    "parse_note_pairs",
    "parse_pc_speaker_preview_tracks",
    "pc_speaker_preview_duration_seconds",
    "play_audio_file",
    "play_audio_item_realtime",
    "render_preview_async",
    "start_audio_preview_async",
    "soundcard_music_header",
    "soundcard_music_offsets",
    "stop_audio_playback",
    "synthesize_soundcard_music_wav",
    "synthesize_wav",
    "synthesize_ym3812_wav",
    "temp_preview_wav",
    "write_midi",
    "write_opl_full_register_trace_csv",
    "write_opl_register_trace_csv",
    "write_opl_vgm",
]
